name: ci

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push agent api
        id: api_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/agentapi/Dockerfile
          push: true
          tags: hackfan/skadi-agent-api:latest
      -
        name: Build and push watcher
        id: watcher_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/lonelywatcher/Dockerfile
          push: true
          tags: hackfan/skadi-watcher:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}