name: ci

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push agent
        id: build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hackfan/skadi-agent:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}